using Pkg
Pkg.status()
print(ENV["PYTHON"])
print(ENV["JULIA_PROJECT"])
Pkg.generate(ENV["JULIA_PROJECT"])
Pkg.activate(ENV["JULIA_PROJECT"])
Pkg.add("ArgParse")
Pkg.add("JSON")
Pkg.add("PowerModels")
Pkg.add(name="Ipopt", version="0.7.0")
Pkg.add(name="CPLEX", version="0.7.8")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("GraphPlot")
Pkg.add("Graphs")
Pkg.add("Cairo")
Pkg.add("Compose")
Pkg.add("XLSX")
Pkg.add(name="JuMP", version="0.21.10")
Pkg.add(name="MathOptInterface" , version="0.9.22")
Pkg.add("Dates")
Pkg.add("LinearAlgebra")
Pkg.add("JLD2")
Pkg.add("OdsIO")
Pkg.build("OdsIO")
Pkg.status() 
exit(); 

